image: drupalpod/drupalpod-gitpod-base:latest

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - name: terminal
    before: |
      .gitpod/ddev-in-gitpod-setup.sh
    init: |
      ddev debug download-images
      .gitpod/project-setup.sh
    command: |
      echo y | ddev start
      gp preview $(gp url 8080)

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client

    # Twig extensions.
    - mblode.twig-language-2

    # Bash extensions.
    - timonwong.shellcheck
    - rogalmic.bash-debug

# Set the following ports public
ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  # Used by MailHog
  - port: 5000
    onOpen: open-preview
  - port: 6006
    onOpen: open-preview
  - port: 6942
    onOpen: ignore
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore
